### ISSUE TITLE
4.12 BadRequestError

### ISSUE THREAD

**Issue by davecorun** [vladris/azure-data-engineering#4]
I have the adxtempcodi19dataset.json file in the same directory but I'm receiving a BadRequestError.

`PS C:\projects\de> az datafactory dataset create --factory-name "adf$suffix" --resource-group adf-rg --name adxtempcovid19dataset --properties '@adxtempcovid19dataset.json'
Command group 'datafactory dataset' is experimental and not covered by customer support. Please use with discretion.
BadRequestError: Operation returned an invalid status 'Bad Request'`

**Comment by davecorun** [comment]
I may have missed a step earlier in creating the Covid19Temp table.

**Comment by vladris** [comment]
I cannot repro this one, seems to be working fine for me. Which version of Azure CLI are you using?

**Comment by davecorun** [comment]
PS C:\Users\david.m.corun> az --version
azure-cli                         2.14.2 *

core                              2.14.2 *
telemetry                          1.0.6

Extensions:
azure-cli-ml                      1.19.0
azure-devops                      0.18.0
datafactory                        0.2.0
kusto                              0.2.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\david.m.corun\.azure\cliextensions'

Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

-------------
This was the latest when I reviewed the book.  It's possible this is resolved with the latest version now.

**Comment by vladris** [comment]
I'll close as no repro.
