### ISSUE TITLE
7.12 pip install azureml-sdk error

### ISSUE THREAD

**Issue by davecorun** [vladris/azure-data-engineering#8]
`PS C:\projects\de> pip install azureml-sdk
Defaulting to user installation because normal site-packages is not writeable
Collecting azureml-sdk
  Using cached azureml_sdk-1.18.0-py3-none-any.whl (4.4 kB)
ERROR: Could not find a version that satisfies the requirement azureml-core~=1.18.0 (from azureml-sdk) (from versions: 0.1.50, 0.1.57, 0.1.58, 0.1.59, 0.1.65, 0.1.68, 0.1.74, 0.1.80, 1.0rc83, 1.0rc85, 1.0.2, 1.0.6, 1.0.8, 1.0.10, 1.0.15, 1.0.17, 1.0.17.1, 1.0.18, 1.0.21, 1.0.23, 1.0.30, 1.0.33, 1.0.33.1, 1.0.39, 1.0.41, 1.0.41.1, 1.0.43, 1.0.43.1, 1.0.45, 1.0.48, 1.0.53, 1.0.55, 1.0.57, 1.0.57.1, 1.0.60, 1.0.62, 1.0.62.1, 1.0.65, 1.0.65.1, 1.0.69, 1.0.72, 1.0.74, 1.0.76, 1.0.76.1, 1.0.79, 1.0.81, 1.0.81.1, 1.0.83, 1.0.85, 1.0.85.1, 1.0.85.2, 1.0.85.3, 1.0.85.4, 1.0.85.5, 1.0.85.6, 1.1.0rc0, 1.1.1rc0, 1.1.1.1rc0, 1.1.1.2rc0, 1.1.2rc0, 1.1.5, 1.1.5.1, 1.1.5.2, 1.1.5.3, 1.1.5.4, 1.1.5.5, 1.1.5.6, 1.1.5.7)
ERROR: No matching distribution found for azureml-core~=1.18.0 (from azureml-sdk)`

**Comment by vladris** [comment]
Upgrading pip using `python -m pip install --upgrade pip` fixed this for me. I'll mention in the book to ensure pip is up to date before running this.
